var user = require("./user/index.js")
var pagesRoute = require("./pagesRoute/index.js")
var dictionarie = require("./dictionarie/index.js")
var menu = require("./menu/index.js")
var role = require("./role/index.js")
var dept = require("./dept/index.js")
var uploadFile = require("./uploadFile/index.js")
var image = require("./image/index.js")
var article = require("./article/index.js")
module.exports = app => {
    app.use('/user',user)
    app.use('/page',pagesRoute)
    app.use('/admin',dictionarie)
    app.use('/admin',menu)
    app.use('/admin',role)
    app.use('/admin',dept)
    app.use('/admin',uploadFile)
    app.use('/admin',image)
    app.use('/admin',article)
}